### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by slhck** [varenc/homebrew-ffmpeg#10]
We should use Travis to make CI automated builds of the formula for:

- macOS 10.12–10.14
- Linux (e.g., Ubuntu LTS)

A good starting point for a `.travis.yml` could be this one: https://github.com/denji/homebrew-nginx/blob/master/.travis.yml

Some other options are visible here: https://github.com/petere/homebrew-postgresql/blob/master/.travis.yml

Not a big expert when it comes to Travis, so I'll have to do some offline testing before.

**Comment by retokromer** [comment]
(I personally do not like Travis, because the noise produced is much bigger than the benefit. Yet if one implements it, then I’m in favour. I’m just not willing to do it myself.)

**Comment by slhck** [comment]
This Dockerfile would install the formula (with options, if necessary):

```
FROM ubuntu:bionic
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl file g++ git locales make uuid-runtime python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -f UTF-8 en_US.UTF-8 \
    && useradd -m -s /bin/bash linuxbrew \
    && echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
WORKDIR /home/linuxbrew
ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH \
    SHELL=/bin/bash

RUN git clone https://github.com/Linuxbrew/brew.git /home/linuxbrew/.linuxbrew/Homebrew \
    && mkdir /home/linuxbrew/.linuxbrew/bin \
    && ln -s ../Homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin/ \
    && brew config

RUN brew tap varenc/ffmpeg \
    && brew install varenc/ffmpeg/ffmpeg
```

We could probably use this and Travis to build a container for testing. Will have to look further…

**Comment by slhck** [comment]
It seems I cannot even set up CI since I don't own this repository.

@varenc and others, I think we should migrate this repository to its own independent organization in the mid-term. This would allow proper permission handling, and also allow maintainers to change over time.

**Comment by retokromer** [comment]
We have chosen the current repository, because it was not possible to publish the formula inside FFmpeg…

**Comment by slhck** [comment]
By independent organization I also meant one independent from FFmpeg, since I guess that ship has sailed. (Maybe they'd reconsider it, but I was thinking of "Homebrew-ffmpeg" or similar.)

**Comment by retokromer** [comment]
>I was thinking of "Homebrew-ffmpeg" or similar.

OK

**Comment by slhck** [comment]
I pinged Chris to have a look at this and provide his input. I don't want to upset anyone in FFmpeg with choosing a name that implies affiliation. I guess we should add an explicit note about that.

**Comment by retokromer** [comment]
>I don't want to upset anyone in FFmpeg

_Mission: Impossible_ ;-)

**Comment by retokromer** [comment]
The formula could also be moved to [AMIA Open Source](https://github.com/amiaopensource) GitHub repository which already hosts [ffmprovisr](https://github.com/amiaopensource/ffmprovisr), [vrecord](https://github.com/amiaopensource/vrecord) and many other tools and ressources.

AMIA = Association of Moving Image Archivists

**Comment by slhck** [comment]
Thanks for the offer/suggestion. Personally, I'd prefer a new organization. I have not heard from @varenc for months now, and I am quite unhappy about not having control over this repo, so I suggest that in the worst case – e.g. in a month from now – we create a fork and update the guides on Trac and perhaps some other pages from where the formula is linked.

**Comment by retokromer** [comment]
>in a month from now

@slhck Any news? This formula is [used](https://formulae.brew.sh/analytics/install-on-request/30d/) with different options (search e.g. `varenc`).

**Comment by slhck** [comment]
No news so far. I did send a follow-up end of June. I'm ready to move forward.

What is your opinion on creating an organization `homebrew-ffmpeg` with the corresponding repository name `homebrew-ffmpeg`, with us as maintainers? I know this is a little verbose when writing out the command to install the 3rd party formula, but people are most likely going to copy-paste it anyway.

As for migrating, we should then change the links [here](https://trac.ffmpeg.org/wiki/CompilationGuide/macOS#Additionaloptions).

To be safe, let's just include a visible note that the organization/repo is not affiliated with the project FFmpeg.

**Comment by retokromer** [comment]
I am fine with `homebrew-ffmpeg/homebrew-ffmpeg` witch in practice can be written as `homebrew-ffmpeg/ffmpeg` when used (the second `homebrew-` is not mandatory).

>To be safe, let's just include a visible note that the organization/repo is not affiliated with the project FFmpeg.

+1

**Comment by slhck** [comment]
Both done, see https://github.com/homebrew-ffmpeg/homebrew-ffmpeg. You have been given owner rights.
