### ISSUE TITLE
Blackmagic decklink support

### ISSUE THREAD

**Issue by wblj** [varenc/homebrew-ffmpeg#19]
It would be very helpful if --enable-decklink were a supported option in this tap! I may be missing something, but I do not see a way to build wit that option. BlackMagic requires the includes to be downloaded by the user, but an option to just point to those includes in the brew command line would be great.

**Comment by slhck** [comment]
This is the same as for NVENC and other third party libraries. I don't know if it's possible to automatically detect if these are present with Homebrew. In the meantime I'd recommend building manually.

**Comment by retokromer** [comment]
See: https://github.com/amiaopensource/homebrew-amiaos/blob/a64213c4df33b65d560e3966aba8e7f8b7f4e7c2/ffmpegdecklink.rb#L135-L139

**Comment by wblj** [comment]
Sadly, that formula fails with "ERROR: Decklink API version must be >= 10.9.5.". I actually do not see where they get the include files from BlackMagic; it seems to me like the FFmpeg release is not correct, but I'm not very knowledgable.

**Comment by retokromer** [comment]
Hmm… It works fine on my end on a fresh installation, and I cannot reproduce. I will try to delve into this during the weekend.

**Comment by slhck** [comment]
I'll file this as an "enhancement" and see if there is a way to enable `:optional` for these libraries which are usually not installed and cannot be installed through Homebrew. The formula Reto has linked to will always include that option (`--enable-decklink`). I suggest moving any discussion about errors with the other formula to its issue tracker.

**Comment by retokromer** [comment]
To my knowledge, the Blackmagic components cannot be installed via Homebrew. We can «only» link them correctly to FFmpeg.

**Comment by slhck** [comment]
Yes, the question is if it works if we simply include:

    option "with-decklink", "Enable linking against decklink"

and:

    args << "--enable-decklink" if …

But what should the `if` condition be? Only a real dependency will be available in `build.with?`.

I don't have a Decklink card to test this with.

**Comment by retokromer** [comment]
If I remember carefully, the licence of Blackmagic is not compatible with FFmpeg’s. I suggest to do here as well what we did in AMIA Open Source:

```ruby
  if build.with? "decklink"
    args << "--enable-nonfree"
    args << "--enable-decklink"
    args << "--extra-cflags=-I#{HOMEBREW_PREFIX}/include"
    args << "--extra-ldflags=-L#{HOMEBREW_PREFIX}/include"
  end
```

**Comment by slhck** [comment]
You're right. That will probably work, but we'll also have to deal with the nonfree flag for fdk-aac and openssl. I suggest moving all nonfree dependencies from this line:

https://github.com/varenc/homebrew-ffmpeg/blob/master/Formula/ffmpeg.rb#L163

to a dedicated block.

**Comment by retokromer** [comment]
Yes, I agree: we should group all in one `--enable-nonfree` flag.

**Comment by ghost** [comment]
Yes, decklink is considered nonfree. See `EXTERNAL_LIBRARY_NONFREE_LIST` and `HWACCEL_LIBRARY_NONFREE_LIST` in `configure` to see nonfree libraries.

**Comment by retokromer** [comment]
>Sadly, that formula fails with "ERROR: Decklink API version must be >= 10.9.5.".

For the records: this has been resolved on [AMIA Open Source](https://github.com/amiaopensource/homebrew-amiaos/issues/171).
