### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by slhck** [varenc/homebrew-ffmpeg#2]
Dependency builds fail under Linux (Ubuntu 18.10) due to:

- [x] https://github.com/Linuxbrew/homebrew-core/issues/11609
- [x] https://github.com/Linuxbrew/homebrew-core/issues/11608
- [x] `shared-mime-info` fails to build: https://github.com/Linuxbrew/homebrew-core/issues/11643
- [x] `args << "--disable-opencl" unless OS.mac?` needs to be added

-----

About opencl, when running `./configure`:

```
ERROR: opencl not found
```

See: https://gist.github.com/slhck/49072930ab3df88e610315a6e61e5b3b

**Comment by iMichka** [comment]
FYI I will make a pass on ffmpeg soon. I know that the formula is broken. But so many options have been removed/added that I lost track of all the details.

Regarding OpenCL I will disable it in Linuxbrew. We never got OpenCL to build, it is really hard to setup on Linux (at least the last time I tried to get it to compile).

**Comment by slhck** [comment]
We can help you with figuring that out! Linuxbrew would be a perfect solution for building ffmpeg. Right now, the Linux world has to resort to lots of different manual, not always up-to-date build scripts, or manually copy-pasting from our wikis, so having a formula would really simplify that process.

As for the Linuxbrew ffmpeg formula, `opencl` just has to be disabled in the configuration flags. Is there any function that can be used to insert that option for the Linux-only part, i.e. anything non-macOS?

**Comment by slhck** [comment]
Oh, I see there's `if OS.mac?`. I'll test that later and see if I can get ffmpeg to build.

**Comment by slhck** [comment]
@iMichka Just a question for clarification: is the plan to have Linuxbrew ship its own formula that is different from the one in Homebrew? Wouldn't it be less complex to have all the requirements (and Linux-related exceptions) baked into the upstream formula? To me it looks like your modifications to `ffmpeg.rb` should be backwards-compatible to upstream.

**Comment by iMichka** [comment]
There are some answers to that question here:
https://discourse.brew.sh/t/is-tap-linuxbrew-core-going-to-be-migrated-to-homebrew-core-as-well/3861

So for the moment the two homebrew-core repositories will stay separated. The Linux version tries to stay as close as possible to the mac version. At least when possible.

**Comment by slhck** [comment]
Got it, thanks for the explanation!

**Comment by slhck** [comment]
Got the build to work with https://github.com/varenc/homebrew-ffmpeg-with-options/pull/3

**Comment by iMichka** [comment]
I do not see that `opencl` flag in the linuxbrew version. Are you using an older version of the formula?

**Comment by slhck** [comment]
Sorry, this thread was about *this* particular tap's formula. It was always aimed at macOS, so it had `opencl` in there. I think @varenc did not take over the conditionals for macOS from upstream that would've prevented the `--enable-opencl` and `--enable-videotoolbox` from showing up under Linux. That's why I put it in a block to make it build on both systems.

The Linuxbrew `ffmpeg` formula has no options and already works fine under Linux (apart from the  fact that for some reason it pulls both `python` and `python2`).

Going forward, the idea is to maintain this tap as an alternative that has build options and third party dependencies. Ideally it'll support both Homebrew and Linuxbrew.

**Comment by iMichka** [comment]
Ok, no problem, got it. Regarding `python` and `python2`, there probably needs to be some cleanup. The dependency tree is a little bit a mess right now for these two formulae. But as `python2` will be gone in January 2020, this problem will probably be solved at that point :)

**Comment by varenc** [comment]
just merged @slhck's #3 PR (and gave him write perms) so I think this is closed!

I'm gonna see if merging in recent commits from the homebrew-core ffmpeg.rb formula is easy, but my guess is they've already diverged enough that the merging will be pretty manual.  They did add a few more dependencies recently we should probably add in soon as well (though probably as options not defaults).
