### ISSUE TITLE
Missing x265 option 

### ISSUE THREAD

**Issue by k06a** [varenc/homebrew-ffmpeg#21]
Any change to get x265 codec?
```
Error: invalid option: --with-x265
```

**Comment by retokromer** [comment]
In the present formula `x265` is enabled by default, therefore you don’t need to pass the parameter `--with-x265`.

**Comment by retokromer** [comment]
You can run:

```
brew options ffmpeg
```

to see the list of supported options for this formula.

See also: https://github.com/varenc/homebrew-ffmpeg#installing-with-options

**Comment by k06a** [comment]
@retokromer thanks!

**Comment by retokromer** [comment]
@k06a You are very welcome!

**Comment by k06a** [comment]
@retokromer updated gist for h265+aac video encoding: https://gist.github.com/k06a/45f4ff4e52a7c0ad2add370ab1a315e7
