### ISSUE TITLE
staticaly linked version

### ISSUE THREAD

**Issue by b005t3r** [varenc/homebrew-ffmpeg#30]
I'd like to use your formula to build ffmpeg (with decklink), but have everything linked staticaly. Is this possible? Could you explain me how do I do it? :)

**Comment by slhck** [comment]
You can find a sample build script here: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu — some of these third-party libraries use static compilation options. Specifically for DeckLink, I don't know how to build it in a static fashion. FFmpeg should then pick up the static lib when built.

Anyway I don't think Homebrew formulae can be easily adapted to perform static compilations, as you'd have to change all third-party dependencies to build statically first. So it's not just about changing this formula. Instead I'd recommend building manually.
