### ISSUE TITLE
Install with all options fails

### ISSUE THREAD

**Issue by cbornhoft** [varenc/homebrew-ffmpeg#38]
Running the recommended command:

    brew install varenc/ffmpeg/ffmpeg $(brew options varenc/ffmpeg/ffmpeg --compact)

Results in:

    ==> Installing ffmpeg from varenc/ffmpeg
    imlib2: XQuartz 2.7.11 (or newer) is required to install this formula. X11Requirement unsatisfied!
    You can install with Homebrew Cask:
      brew cask install xquartz
    You can download from:
      https://xquartz.macosforge.org
    Error: An unsatisfied requirement failed this build.

Looks like a new dependency is required for one of the libraries.

After installing the recommended cask, it appears to work up to the point of:

    ==> Installing varenc/ffmpeg/ffmpeg --with-chromaprint --with-decklink --with-fdk-aac --with-librsvg --with-libsoxr --with-libssh --with-t
    ==> Downloading https://ffmpeg.org/releases/ffmpeg-4.1.4.tar.xz
    ######################################################################## 100.0%
    ==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.1.4-with-options --enable-shared --cc=clang --host-cflags=-I/System/Library/Frameworks/JavaVM.fr
    Last 15 lines from /Users/chris/Library/Logs/Homebrew/ffmpeg/01.configure:
    --extra-ldflags=-L/usr/local/include
    --enable-version3
    --enable-libopencore-amrnb
    --enable-libopencore-amrwb
    --enable-libopenjpeg
    --disable-decoder=jpeg2000
    --extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3

    ERROR: DeckLinkAPI.h not found

    If you think configure made a mistake, make sure you are using the latest
    version from Git.  If the latest version fails, report the problem to the
    ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
    Include the log file "ffbuild/config.log" produced by configure as this will help
    solve the problem.

    If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
      https://github.com/varenc/homebrew-ffmpeg/issues

**Comment by slhck** [comment]
Note that this repo is not actively maintained. See: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg for an updated one.

I'm getting the "install everything" option removed, it's not very useful, since for some libraries (like Decklink) you need the appropriate hardware and SDK.
