### ISSUE TITLE
Error: varenc/ffmpeg/ffmpeg contains a recursive dependency on itself:

### ISSUE THREAD

**Issue by maxgronlund** [varenc/homebrew-ffmpeg#39]
Error: varenc/ffmpeg/ffmpeg contains a recursive dependency on itself:
  varenc/ffmpeg/ffmpeg depends on chromaprint
  chromaprint depends on varenc/ffmpeg/ffmpeg

**Comment by slhck** [comment]
This project is not maintained anymore, see https://github.com/homebrew-ffmpeg/homebrew-ffmpeg
