### ISSUE TITLE
Additional options for Linux

### ISSUE THREAD

**Issue by retokromer** [varenc/homebrew-ffmpeg#4]
I notice that we have also:

```rb
  unless OS.mac?
    depends_on "zlib"
    depends_on "bzip2"
    depends_on "linuxbrew/xorg/libxv"
  end
```

in our flavour (aka my company’s), but I cannot remember why at the moment. Any thoughts?

Does it compile carefully without it on your end, @slhck?

**Comment by slhck** [comment]
Good point. Especially `libxv` could be relevant for X11. It compiles without that, but the build may be missing some functionality. About the compression libraries, I'll check as well.

**Comment by retokromer** [comment]
Resolved in https://github.com/varenc/homebrew-ffmpeg-with-options/pull/5 by @slhck. Thank you!
