### ISSUE TITLE
FFmpeg depends on itself via --with-chromaprint

### ISSUE THREAD

**Issue by fmgjcoppens** [varenc/homebrew-ffmpeg#42]
Dear varenc,

There seems the be a circular dependency through '--with-chromaprint'

==> Installing ffmpeg from varenc/ffmpeg
Error: varenc/ffmpeg/ffmpeg contains a recursive dependency on itself:
  varenc/ffmpeg/ffmpeg depends on chromaprint
  chromaprint depends on varenc/ffmpeg/ffmpeg

The formula install if '--with-chromaprint' is omitted from the list of options:

brew install varenc/ffmpeg/ffmpeg --HEAD --with-decklink --with-fdk-aac --with-game-music-emu --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvmaf --with-libxml2 --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rtmpdump --with-rubberband --with-speex --with-srt --with-tesseract --with-two-lame --with-wavpack --with-webp --with-xvid --with-zeromq --with-zimg

Kind regards,
François

**Comment by slhck** [comment]
This repo is no longer maintained, see https://github.com/homebrew-ffmpeg/homebrew-ffmpeg instead.
