### ISSUE TITLE
Rename to homebrew-ffmpeg

### ISSUE THREAD

**Issue by slhck** [varenc/homebrew-ffmpeg#6]
According to https://discourse.brew.sh/t/renaming-a-tap/4188 we can simply rename via GitHub.

I propose renaming to `homebrew-ffmpeg`.

This should be done:

- [ ] Rename on GitHub
- [ ] Update links on trac.ffmpeg.org/wiki
- [ ] Add new instructions to README
- [ ] Optionally: Add renaming instructions with `brew untap` to README

**Comment by retokromer** [comment]
+1

**Comment by varenc** [comment]
just pulled off most of this! importantly I confirmed that any users still referencing the old tap will continue working.

* [X]  Rename on GitHub
* [X]  Update links on trac.ffmpeg.org/wiki
* [X]  Add new instructions to README
* [ ]  Optionally: Add renaming instructions with `brew untap` to README

**Comment by varenc** [comment]
updated the readme as well

- [X] Optionally: Add renaming instructions with brew untap to README

**Comment by retokromer** [comment]
Thank you!
